### ISSUE TITLE
Algorithms like (U F)99999 cause massive delays

### ISSUE THREAD

**Issue by rokicki** [cubing/twizzle.js#5]
We should probably try to avoid every expanding a full algorithm; we should be able to do everything we need "algebraically".

**Comment by lgarron** [comment]
The API of [`cursor.ts`](https://github.com/cubing/twisty.js/blob/master/src/cursor.ts) is designed to allow this efficiently, although the implementation currently still expands the alg internally. We'll have to build up a data structure to scrobble through a nested alg.

**Comment by rokicki** [comment]
Solved in new twizzle that's in cubing.js.
